### ISSUE TITLE
How to start this thing up?

### ISSUE THREAD

**Issue by FrazeColder** [213a/StoreDuplicator#11]
Hey there,

somehow I always get this error
```
Could not validate proper store setup Response code 401 (Unauthorized)
```

But I have correctly created two apps and have copied the app key and app password. 
<img width="1245" alt="Bildschirmfoto 2024-08-14 um 21 33 26" src="https://github.com/user-attachments/assets/9294670f-04ea-42cd-a088-44b5c7fc826a">

Can you please help me?

Kind regards

**Comment by alexleclair** [comment]
Hi!
You need to use the access token as the password (the first value with dots and blacked out in your screenshot).

Since the access token was revealed, you may need to uninstall and reinstall your app to generate a new token

**Comment by FrazeColder** [comment]
Perfect, thank you!
